repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/returntocorp/semgrep
    rev: "v0.29.0"
    hooks:
      - id: semgrep
        # See semgrep.dev/rulesets to select a ruleset and copy its URL
        args: ["--config", "https://semgrep.dev/p/bandit", "--error"]

  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: isort
        types: [python]

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pytest
        types: [python]
        always_run: true
        pass_filenames: false # See [here](https://github.com/pre-commit/pygrep-hooks/blob/eb0a92ce09636b6d72787952ce0f74c5dad996fa/.pre-commit-config.yaml#L47-L53)
